server:
  port: 80
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: Jeff302132
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.jeff.springbot.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl