server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: Jeff302132
    driver-class-name: com.mysql.jdbc.Driver

user:
  jeff:
    age: 18
    name: 杨剑辉